export const keywordsMap = {
  частота: {column: "base_clock", type: "integer"},
  сокет: {column: "socket", type: "text"},
  "количество ядер": {column: "cores", type: "integer"},
  тепловыделение: {column: "tdp", type: "integer"},
  бренд: {column: "brand", type: "text"},
  "количество потоков": {column: "threads", type: "integer"},
  "объем видеопамяти": {column: "vram", type: "integer"},
  "максимальное энергопотребление": {column: "tdp", type: "integer"},
  чипсет: {column: "chipset", type: "text"},
  "форм-фактор поддерживаемой памяти": {column: "form_factor", type: "text"},
  "тип памяти": {column: "ram_type", type: "text"},
  "количество слотов памяти": {column: "ram_slots", type: "integer"},
  "максимальный объем оперативной памяти": {column: "max_ram", type: "integer"},
  типоразмер: "form_factor",
  "максимальная длина видеокарты": {column: "gpu_length_limit", type: "integer"},
  "максимальная высота кулера процессора": {column: "cooler_height_limit", type: "integer"},
  socket: {column: "socket_support", type: "textArray"},
  мощность: {column: "wattage", type: "integer"},
  "сертифицирован в стандарте": {column: "certification", type: "text"},
  "отсоединяющиеся кабели": {column: "modular", type: "boolean"},
  "объем одного модуля": {column: "capacity", type: "integer"},
  скорость: {column: "speed", type: "integer"},
  "объем накопителя": {column: "capacity", type: "integer"},
  интерфейс: {column: "interface", type: "text"},
};